[package]
name = "tasu"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
description = "A terminal todo list manager built with ratatui"
license = "Apache-2.0"
repository = "https://github.com/mancuoj-collective/tasu"
readme = "README.md"
keywords = ["tui", "todo", "ratatui", "terminal", "cli"]
categories = ["command-line-utilities"]
authors = ["mancuoj <mancuoj@gmail.com>"]

[dependencies]
anyhow = "1.0.104"
crossterm = "0.29.0"
ratatui = "0.30.2"

# Read the optimization guideline for more details: https://ratatui.rs/recipes/apps/release-your-app/#optimizations
[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
